services:
  wordpress:
    build: ./wordpress
    container_name: wp_fpm
    restart: always
    environment:
      DB_USER: wordpress
      DB_PASS: wordpress
      DB_NAME: wordpress
      DB_HOST: mariadb
      WP_USER: admin
      WP_PASS: admin123
    volumes:
      - wp_data:/var/www/html

  nginx:
    image: nginx:latest
    container_name: wp_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - wp_data:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress

  mariadb:
    image: mariadb:latest
    container_name: wp_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wp_data:
  db_data:

